# Generated by Django 2.0.2 on 2018-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180509_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceold',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
