# Generated by Django 2.0.2 on 2018-05-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_priceold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decrease',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
