# Generated by Django 2.0.2 on 2018-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_decrease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceold',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
