# Generated by Django 2.0.2 on 2018-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=True),
        ),
    ]
