# Generated by Django 2.0.2 on 2018-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decrease',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
