# Generated by Django 2.0.2 on 2018-04-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180428_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Họ',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tên',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Địa chỉ nhận hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
